import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body suppressHydrationWarning className="min-h-screen flex flex-col overflow-x-hidden">
        <Script id="strip-extension-attrs" strategy="beforeInteractive">
          {`(() => {
            const attrPattern = /^(bis_|fdprocessedid$|__processed_|data-new-gr-c-s-check-loaded$|data-gr-ext-installed$)/;

            const scrub = (root) => {
              if (!root || !root.querySelectorAll) return;

              const allNodes = [root, ...root.querySelectorAll('*')];
              for (const node of allNodes) {
                for (const attr of Array.from(node.attributes || [])) {
                  if (attrPattern.test(attr.name)) {
                    node.removeAttribute(attr.name);
                  }
                }
              }
            };

            scrub(document.documentElement);
          })();`}
        </Script>
        {children}
      </body>
    </html>
  );
}
